name: Release Windows Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - name: Build Windows executable
        run: go build -ldflags="-s -w" -o translator.exe .
        env:
          GOOS: windows
          GOARCH: amd64

      - name: Compress executable with UPX
        run: upx --best --lzma -o translator_compressed.exe translator.exe

      - name: Package executable in a zip file
        run: |
          mv LICENSE LICENSE.txt
          zip translator-windows-amd64.zip translator_compressed.exe README.md LICENSE.txt

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: translator-windows-amd64.zip
          body: "Automated release of the Windows executable."
